#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BandWorld.MVC
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "_SubView.cshtml"
using JTRazorPortable;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class _SubView : ViewBase
{

#line hidden

#line 3 "_SubView.cshtml"
public BandWorld.MVC.Models.MainViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<p>\n    This is the text from the sub-view: ");


#line 6 "_SubView.cshtml"
                                   Write(Model.Text);


#line default
#line hidden
WriteLiteral(".\n</p>\n");

}
}
}
#pragma warning restore 1591
