#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BandWorld.MVC
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class _TestAjax : JTRazorPortable.ViewBase
{

#line hidden

#line 2 "_TestAjax.cshtml"
public string Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 3 "_TestAjax.cshtml"
   Layout = null; 

#line default
#line hidden
WriteLiteral("\nAjax: ");


#line 4 "_TestAjax.cshtml"
 Write(Model);


#line default
#line hidden
WriteLiteral("\n");

}
}
}
#pragma warning restore 1591
