#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BandWorld.MVC
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "About.cshtml"
using JTRazorPortable;

#line default
#line hidden

#line 2 "About.cshtml"
using BandWorld.MVC.Helpers;

#line default
#line hidden

#line 3 "About.cshtml"
using BandWorld.MVC.Models;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class About : ViewBase
{

#line hidden

#line 6 "About.cshtml"
public MainViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 8 "About.cshtml"
  
    // Specify our layout, which defaults to "_Layout" unless we set an empty string here.
    Layout = "~/Views/Shared/_Layout.cshtml";



#line default
#line hidden
WriteLiteral("    <h1>\n");

WriteLiteral("        ");


#line 13 "About.cshtml"
   Write(this.S("About JTMobile"));


#line default
#line hidden
WriteLiteral("\n    </h1>\n");

WriteLiteral("    <p>\n");

WriteLiteral("        ");


#line 16 "About.cshtml"
   Write(this.S("Just an experimental app."));


#line default
#line hidden
WriteLiteral("\n    </p>\n");


#line 18 "About.cshtml"

    Html.MessageDiv("This is a message.", "This is an error.");


#line default
#line hidden
WriteLiteral("\n");

}
}
}
#pragma warning restore 1591
