#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BandWorld.MVC
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "_Layout.cshtml"
using JTRazorPortable;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class _Layout : ViewBase
{

#line hidden

public override void Execute()
{

#line 4 "_Layout.cshtml"
  


#line default
#line hidden
WriteLiteral("\n<!DOCTYPE html>\n<html>\n<head>\n\t<meta");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral("/>\n\t<meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral("/>\n");

WriteLiteral("    ");


#line 11 "_Layout.cshtml"
Write(Styles.Render("~/Content/css"));


#line default
#line hidden
WriteLiteral("\n");

WriteLiteral("    ");


#line 12 "_Layout.cshtml"
Write(Scripts.Render("~/bundles/scripts"));


#line default
#line hidden
WriteLiteral("\n</head>\n<body>\n    <div");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\n");

WriteLiteral("        ");


#line 16 "_Layout.cshtml"
   Write(Html.Partial("_MainHeader"));


#line default
#line hidden
WriteLiteral("\n    </div>\n    <div");

WriteLiteral(" class=\"renderbody\"");

WriteLiteral(">\n");

WriteLiteral("        ");


#line 19 "_Layout.cshtml"
   Write(RenderBody());


#line default
#line hidden
WriteLiteral("\n    </div>\n");

WriteLiteral("    ");


#line 21 "_Layout.cshtml"
Write(RenderSection("scripts", required: false));


#line default
#line hidden
WriteLiteral("\n    <p>\n");

WriteLiteral("        ");


#line 23 "_Layout.cshtml"
   Write(Html.Partial("_MainFooter"));


#line default
#line hidden
WriteLiteral("\n    </p>\n</body>\n</html>\n");

}
}
}
#pragma warning restore 1591
