#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BandWorld.MVC
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "_MainFooter.cshtml"
using JTRazorPortable;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class _MainFooter : ViewBase
{

#line hidden

public override void Execute()
{
WriteLiteral("This is my footer.\n\n");

}
}
}
#pragma warning restore 1591
