#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BandWorld.MVC
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "_MainHeader.cshtml"
using JTRazorPortable;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class _MainHeader : ViewBase
{

#line hidden

public override void Execute()
{

#line 4 "_MainHeader.cshtml"
  
    string applicationName = "JTMobile";


#line default
#line hidden
WriteLiteral("\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n        </button>\n");

WriteLiteral("        ");


#line 14 "_MainHeader.cshtml"
   Write(Html.ActionLink(@applicationName, "Index", "Test", new { area = "" }, new { @class = "navbar-brand" }));


#line default
#line hidden
WriteLiteral("\n    </div>\n    <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\n        <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\n            <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">Submenu</a>\n                <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral(">\n                    <li>");


#line 21 "_MainHeader.cshtml"
                   Write(Html.ActionLink("Test", "Test", "Test"));


#line default
#line hidden
WriteLiteral("</li>\n                </ul>\n            </li>\n            <li>");


#line 24 "_MainHeader.cshtml"
           Write(Html.ActionLink("About", "About", "Test"));


#line default
#line hidden
WriteLiteral("</li>\n        </ul>\n    </div>\n</div>\n");

}
}
}
#pragma warning restore 1591
