#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BandWorld.MVC
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "Error.cshtml"
using JTRazorPortable;

#line default
#line hidden

#line 3 "Error.cshtml"
using BandWorld.MVC.Helpers;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class Error : ViewBase
{

#line hidden

#line 5 "Error.cshtml"
public string Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("\n");


#line 7 "Error.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";
    string message = (!String.IsNullOrEmpty(Model) ? Model : "(Sorry, no more details available.)");


#line default
#line hidden
WriteLiteral("\n\n<h2>Error</h2>\n<h4>An error occured.</h4>\n<p>\n    <center>");


#line 15 "Error.cshtml"
       Write(message);


#line default
#line hidden
WriteLiteral("</center>\n</p>\n<p>\n");

WriteLiteral("    ");


#line 18 "Error.cshtml"
Write(Html.ActionLinkWithImage("Back.png", "Back", "Back", "Test", null));


#line default
#line hidden
WriteLiteral("\n</p>\n");

}
}
}
#pragma warning restore 1591
